# NatLibFi/KB maintenance strategy v2

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "test"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase-if-necessary
    target-branch: "test"
    groups:
      major-updates:
        update-types: ["major"]
      minor-updates:
        update-types: ["minor", "patch"]
    pull-request-branch-name:
      separator: "-"
